# ------ root_path/dataset_name ------
root_path: 'data'

# ------ Basic Config ------
dataset: 'modelnet40'
shots: 16
backbone: 'ViT-B/16'
backbone_name: 'vit_b16'

subsample_classes: 'base'
augment_epoch: 1

num_views: 10