# ------ root_path/dataset_name ------
root_path: "data"

# ------ Basic Config ------
dataset: "scanobjectnn"
shots: 16
backbone: "ULIP_VITB16"
backbone_name: "vit_b16"

subsample_classes: "base"
augment_epoch: 1

num_views: 10
